AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  carousel-api

  Sample SAM Template for carousel-api
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 128

Resources:
  CarouselFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: carousel/
      Handler: app.getImagesHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Events:
        Carousel:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /api/carousel
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CarouselApi:
    Description: "API Gateway endpoint URL for Prod stage for Carousel function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  CarouselFunction:
    Description: "Carousel Lambda Function ARN"
    Value: !GetAtt CarouselFunction.Arn
  # CarouselFunctionIamRole:
  #   Description: "Implicit IAM Role created for Carousel function"
  #   Value: !GetAtt CarouselFunctionIamRole.Arn
